# Create image based on the official Node 6 image from dockerhub
FROM node:7.9-alpine

MAINTAINER javipg92@gmail.com

# Create a directory where our app will be placed
RUN mkdir -p /project && npm install -g typescript@2.3

# Change directory so that our commands run inside this new directory
WORKDIR /usr/src/app

# Copy dependency definitions
COPY package.json /usr/src/app

# Install dependecies
RUN npm install

# Expose the port the app runs in
EXPOSE 4200

# Serve the app
CMD ["npm", "start"]